#!/usr/bin/env bash

###################################################################
# Script Name : bandwith
# Description : Script to monitor network bandwith in i3blocks.
# Args        : $1 interval between updates, in seconds. Must be a number.
# Author      : CarlesCN
# E-mail      : carlesbioinformatics@gmail.com
# License     : GNU General Public License v3.0
###################################################################

set -e -u -o pipefail

# Labels
#labels=('' '')
#labels=('󰶼' '󰶹')
labels=('󰶣' '󰶡')

# Control arguments
bad_args='This scripts only accepts one argument and it must be a number.'

case $# in
  0) timer=1
     ;;
  1) if [[ $1 =~ ^[0-9]*$ ]]; then
       timer=$1;
     else
       echo "${bad_args}"
       exit 1
     fi
     ;;
  *) echo 'Too many arguments!'
     echo "${bad_args}"
     exit 1
     ;;
esac


# Print lines
while true;
  do cat /proc/net/dev;
  sleep "$timer";
done | awk -v timer="$timer" -v label_up="${labels[0]}" -v label_down="${labels[1]}" \
'
  function printDelta(bytes, last) {
    bits = ((bytes - last) * 8) / timer

    if(     bits > 1024**3) { printf "%3iGb", (bits / (1024 ** 3)) }
    else if(bits > 1024**2) { printf "%3iMb", (bits / (1024 ** 2)) }
    else if(bits > 1024)    { printf "%3iKb", (bits / 1024) }
    else                    { printf "%4ib", bits }
  }

  # First line would show the amount of data transmitted since system started.
  BEGIN { firstLine = 0 }

  # TODO: parametrize device name
  /^enp6s0:/ {
	if (firstLine) {
	  printDelta($2,  lastR); printf "%1s ", label_up
	  printDelta($10, lastT); printf "%1s\n", label_down
	} else {
	  firstLine = 1
	}

    lastR = $2;
    lastT = $10;
  }
  fflush(stdout)
'
