#!/usr/bin/env bash

###################################################################
# Script Name : nordvpn
# Description : Script to monitor the status of NordVPN in i3blocks.
# Args        : None
# Author      : CarlesCN
# E-mail      : carlesbioinformatics@gmail.com
# License     : GNU General Public License v3.0
###################################################################

set -e -u -o pipefail

# Define colors
red="#ff0000"
green="#00ff00"


# Get NordVPN info
# Status line has some invisible fields prefixed (wtf?)
status=$(nordvpn status | awk '/Status:/ {print $4}')
text_server=$(nordvpn status | awk -F'[ .]' '/^Hostname:/ {print $2}')
text_ip=$(nordvpn status | awk '/^IP:/ {print $2}')

# Defautlt text: short server name
text=$text_server

# Respond to mouse events
if [[ -v BLOCK_BUTTON ]]; then
  case ${BLOCK_BUTTON} in
    1) #Left
       # Toggle text: IP / server name
       if [[ -v full_text ]] && ! [[ "${full_text}" =~ ^..[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$ ]]; then
         text=$text_ip
       fi
       ;;
   #2) #Middle
   #3) #Right
   #4) #Scroll Up
   #5) #Scroll Down
   #8) #Upper Thumb
   #9) #Lower Thumb
   #6,7,10+) #Custom
  esac
fi

# Show status (disconnected)
if [[ "${status}" == Disconnected ]]; then
  echo " Disconnected"
  echo "" #short text
  echo "${red}"
  exit 33 # send alert to i3bar
fi

# Show status (connected)
echo " ${text}"
echo "" #short text
echo "${green}"
