#!/usr/bin/env bash

###################################################################
# Script Name : window_title
# Description : Script for i3blocks to display focused window title.
#             : Subscrive to i3 events and updates on every window / workspace change.
#             : Adapted from https://github.com/vivien/i3blocks-contrib/blob/master/sway-focusedwindow/sway-focusedwindow
# Args        : None
# Author      : CarlesCN
# E-mail      : carlesbioinformatics@gmail.com
# License     : GNU General Public License v3.0
###################################################################

set -e -u -o pipefail

# Empty string on desktop init
echo ""


# Build query
# Clean on closing window
query="if .change == \"close\" then \"\" else "

# Show title name
query+='select ( (.container.focused or .current.focused) and (.change == "focus" or .change == "title" or .change == "close") ) | .container.name[0:60] // ""'
# Show class name
#query+='select ( (.container.focused or .current.focused) and .change == "focus" ) | .container.window_properties.class // ""'

# Close if
query+=" end"


# Subscribe to events
i3-msg -m -t subscribe '["window", "workspace"]' | jq --unbuffered -r "${query}"
