#!/usr/bin/env bash

###################################################################
# Script Name : window_title
# Description : Script for i3blocks to display focused window title.
#             : Adapted from https://github.com/vivien/i3blocks-contrib/blob/master/sway-focusedwindow/sway-focusedwindow
# Args        : None
# Author      : CarlesCN
# E-mail      : carlesbioinformatics@gmail.com
# License     : GNU General Public License v3.0
###################################################################

set -e -u -o pipefail

# Focused window on script init
i3-msg -t get_tree | jq --unbuffered -r '.. | select(.focused?) | .name'


# Update title for each focus update

# Title name
query='select ( (.container.focused or .current.focused) and (.change == "focus" or .change == "title")) | .container.name[0:100] // ""'
# Class name
#query='select ( (.container.focused or .current.focused) and .change == "focus") | .container.window_properties.class // ""'

i3-msg -m -t subscribe '["window", "workspace"]' | jq --unbuffered -r "${query}"
